### PR TITLE
Add support for long filepaths on Windows

### PR DESCRIPTION
**Pull request by charlievieth**
This commit uses the [fs](https://github.com/charlievieth/fs) package to add support for filepaths greater than MAX_PATH on Windows.

[#121239765]

### CODE REVIEW

**Comment by benmoss** [comment]
This fixes streaming in deep directory structures, as is pretty common in our Golang vendor-within-vendor-within-vendor-within-vendor [directory hell](https://github.com/cloudfoundry/bosh-agent/tree/b75f0663ec2c324df04049b0691f7832631cef3c/vendor/github.com/cloudfoundry/bosh-utils/vendor/github.com/onsi/ginkgo/integration/_fixtures/convert_fixtures/nested_without_gofiles/subpackage). This uses UNC paths which Windows will let be longer than 256 characters (https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx).

**Comment by benmoss** [comment]
pingu

would be great to get this merged/bumped in concourse/bin so we can get some bosh-deployed windows concourse workers

**Comment by benmoss** [comment]
@vito the suspense is killing us

**Comment by vito** [comment]
my bad. github unwatched all my repos or something and i am nothing without notifications.

merging

**Pull request merged**
